######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 21:02:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

QT += sql
